// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCtR8-pJFMBITzjaRfwRRIEOlR_lt1HHI',
    appId: '1:1042485950826:web:b466cfe984f5977f508d13',
    messagingSenderId: '1042485950826',
    projectId: 'oncard-ad17b',
    authDomain: 'oncard-ad17b.firebaseapp.com',
    storageBucket: 'oncard-ad17b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNing4QKrq64_zGIA1ZDNicKrTjJectcY',
    appId: '1:1042485950826:android:81f45df0d9c8b1af508d13',
    messagingSenderId: '1042485950826',
    projectId: 'oncard-ad17b',
    storageBucket: 'oncard-ad17b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnU5HNhAHi68WofH1LDnimA4y1rHJz-Tk',
    appId: '1:1042485950826:ios:db39ad51a263133d508d13',
    messagingSenderId: '1042485950826',
    projectId: 'oncard-ad17b',
    storageBucket: 'oncard-ad17b.firebasestorage.app',
    iosBundleId: 'com.example.saku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnU5HNhAHi68WofH1LDnimA4y1rHJz-Tk',
    appId: '1:1042485950826:ios:db39ad51a263133d508d13',
    messagingSenderId: '1042485950826',
    projectId: 'oncard-ad17b',
    storageBucket: 'oncard-ad17b.firebasestorage.app',
    iosBundleId: 'com.example.saku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCtR8-pJFMBITzjaRfwRRIEOlR_lt1HHI',
    appId: '1:1042485950826:web:24c96b044a4498be508d13',
    messagingSenderId: '1042485950826',
    projectId: 'oncard-ad17b',
    authDomain: 'oncard-ad17b.firebaseapp.com',
    storageBucket: 'oncard-ad17b.firebasestorage.app',
  );
}
